package util;

/**
 * Created by IntelliJ IDEA.
 * User: Tatyana
 * Date: 09.10.2012
 * Time: 22:48:20
 * To change this template use File | Settings | File Templates.
 */
public interface AllConstantsAttribute {
    String PERSON_ATTRIBUTE = "person";
    String PERSON_ANSWERED_QUESTIONS = "PERSON_ANSWERED_QUESTIONS";
    String WRONG_LOGIN_MESSAGE_ATTRIBUTE = "wrongLoginMessage";
    String PERSON_LIST_ATTRIBUTE = "personList";
    String SIZE = "SIZE";
    String NEW_PERSON_ATTRIBUTE = "newPerson";
    String MESSAGE_ATTRIBUTE = "message";
    String EDIT_PARAM = "Edit";
    String QUESTION_ENTRIES_ATTRIBUTE = "QUESTION_ENTRIES_ATTRIBUTE";
    String QUESTION_ENTRY_ATTRIBUTE = "QUESTION_ENTRY_ATTRIBUTE";
    String CATEGORY_ATTRIBUTE = "CATEGORY_ATTRIBUTE";
    String NEXT_CATEGORY = "NEXT_CATEGORY";
    String PREVIOUS_CATEGORY = "PREVIOUS_CATEGORY";
    String ARTICLE_ATTRIBUTE = "ARTICLE_ATTRIBUTE";
    String ARTICLES = "ARTICLES";
    String TEST_ID_ATTRIBUTE = "TEST_ID_ATTRIBUTE";
    String TEST_PATHS_ATTRIBUTE = "TEST_PATHS_ATTRIBUTE";
    String TESTS = "TESTS";
    String TESTS_WITH_TESTS = "TESTS_WITH_TESTS";
    String COURSES_WITH_QUESTIONS = "COURSES_WITH_QUESTIONS";
    String DUPLICATE_CATEGORIES = "DUPLICATE_CATEGORIES";
    String CATEGORIES = "CATEGORIES";
    String CATEGORY_PATHS_ATTRIBUTE = "CATEGORY_PATHS_ATTRIBUTE";
    String CURRENT_EXAM_ATTRIBUTE = "CURRENT_EXAM_ATTRIBUTE";
    String USER_NAME = "USER_NAME";
    String USER_TEST_EXAMS = "USER_TEST_EXAMS";
    String SOME_USER = "SOME_USER";
    String LANGUAGES = "LANGUAGES";
    String LOCALE = "LOCALE";
}
